run:
  timeout: 3m
  build-tags:
    - vet
  tests: false
  skip-dirs:
    - gpu
    - bin
    - .gocache

issues:
  exclude-dirs:
    - examples
  exclude-files:
    - io/performance.go

linters:
  disable-all: true
  enable:
    - govet
